version: '3.4'

services:
  securedav:
    image: mthalmann/securedav
    depends_on:
      - database
      - redis
    ports:
      - 8080:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_DATABASE=securedav
      - DB_USERNAME=usersecuredav
      - DB_PASSWORD=secret

      - REDIS_HOST=redis
      - REDIS_PASSWORD=redissecret

      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis

      - TZ=UTC
    volumes:
      - ./files:/var/www/html/storage/app/files
      - ./logs:/var/www/html/storage/logs
      - ./.env:/var/www/html/.env
    restart: always

  database:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=securedav
      - MYSQL_USER=usersecuredav
      - MYSQL_PASSWORD=secret
    volumes:
      - ./database:/var/lib/mysql:Z
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass redissecret
    volumes:
      - redis:/data
    restart: always

volumes:
  files:
  logs:
  database:
  redis:
